// The file contains all method messages for AMQP class Exchange (id: 40)
//
// File was auto-generated by generate_bindings.dart at 2019-03-21 11:46:08.129595
//
// Do not modify

// ignore_for_file: empty_constructor_bodies

part of dart_amqp.protocol;

class ExchangeDeclare implements Message {
  final bool msgHasContent = false;
  final int msgClassId = 40;
  final int msgMethodId = 10;

  // Message arguments
  int reserved_1;
  String exchange;
  String type;
  bool passive;
  bool durable;
  bool reserved_2;
  bool reserved_3;
  bool noWait;
  Map<String, Object> arguments;

  ExchangeDeclare();

  void serialize(TypeEncoder encoder) {
    encoder
      ..writeUInt16(msgClassId)
      ..writeUInt16(msgMethodId)
      ..writeUInt16(reserved_1)
      ..writeShortString(exchange)
      ..writeShortString(type)
      ..writeBits([passive, durable, reserved_2, reserved_3, noWait])
      ..writeFieldTable(arguments);
  }
}

class ExchangeDeclareOk implements Message {
  final bool msgHasContent = false;
  final int msgClassId = 40;
  final int msgMethodId = 11;

  // Message arguments

  ExchangeDeclareOk.fromStream(TypeDecoder decoder) {}

  void serialize(TypeEncoder encoder) {}
}

class ExchangeDelete implements Message {
  final bool msgHasContent = false;
  final int msgClassId = 40;
  final int msgMethodId = 20;

  // Message arguments
  int reserved_1;
  String exchange;
  bool ifUnused;
  bool noWait;

  ExchangeDelete();

  void serialize(TypeEncoder encoder) {
    encoder
      ..writeUInt16(msgClassId)
      ..writeUInt16(msgMethodId)
      ..writeUInt16(reserved_1)
      ..writeShortString(exchange)
      ..writeBits([ifUnused, noWait]);
  }
}

class ExchangeDeleteOk implements Message {
  final bool msgHasContent = false;
  final int msgClassId = 40;
  final int msgMethodId = 21;

  // Message arguments

  ExchangeDeleteOk.fromStream(TypeDecoder decoder) {}

  void serialize(TypeEncoder encoder) {}
}
