// The file contains all method messages for AMQP class Exchange (id: 40)
//
// File was auto-generated by generate_bindings.dart at 2019-03-21 11:46:08.129595
//
// Do not modify

// ignore_for_file: empty_constructor_bodies

part of dart_amqp.protocol;

class ExchangeDeclare implements Message {
  @override
  final bool msgHasContent = false;
  @override
  final int msgClassId = 40;
  @override
  final int msgMethodId = 10;

  // Message arguments
  int reserved_1 = 0;
  String? exchange;
  String? type;
  bool passive = false;
  bool durable = false;
  bool reserved_2 = false;
  bool reserved_3 = false;
  bool noWait = false;
  Map<String, Object>? arguments;

  ExchangeDeclare();

  @override
  void serialize(TypeEncoder encoder) {
    encoder
      ..writeUInt16(msgClassId)
      ..writeUInt16(msgMethodId)
      ..writeUInt16(reserved_1)
      ..writeShortString(exchange)
      ..writeShortString(type)
      ..writeBits([passive, durable, reserved_2, reserved_3, noWait])
      ..writeFieldTable(arguments);
  }
}

class ExchangeDeclareOk implements Message {
  @override
  final bool msgHasContent = false;
  @override
  final int msgClassId = 40;
  @override
  final int msgMethodId = 11;

  // Message arguments

  ExchangeDeclareOk.fromStream(TypeDecoder decoder) {}

  @override
  void serialize(TypeEncoder encoder) {}
}

class ExchangeDelete implements Message {
  @override
  final bool msgHasContent = false;
  @override
  final int msgClassId = 40;
  @override
  final int msgMethodId = 20;

  // Message arguments
  int reserved_1 = 0;
  String? exchange;
  bool ifUnused = false;
  bool noWait = false;

  ExchangeDelete();

  @override
  void serialize(TypeEncoder encoder) {
    encoder
      ..writeUInt16(msgClassId)
      ..writeUInt16(msgMethodId)
      ..writeUInt16(reserved_1)
      ..writeShortString(exchange)
      ..writeBits([ifUnused, noWait]);
  }
}

class ExchangeDeleteOk implements Message {
  @override
  final bool msgHasContent = false;
  @override
  final int msgClassId = 40;
  @override
  final int msgMethodId = 21;

  // Message arguments

  ExchangeDeleteOk.fromStream(TypeDecoder decoder) {}

  @override
  void serialize(TypeEncoder encoder) {}
}
